# Generated by Django 4.0.4 on 2022-05-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='file',
            field=models.FileField(upload_to='blog/upload', verbose_name='Файл'),
        ),
    ]
