# Generated by Django 4.0.4 on 2022-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_games_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.FileField(default=1, upload_to='upload', verbose_name='картинка'),
            preserve_default=False,
        ),
    ]
